FROM dougpuob/windows-10-20h2:latest


# Change working direcotry.
WORKDIR "C:\Temp"


# Install essential utilities
RUN choco install -y visualstudio2022community --package-parameters "--allWorkloads --includeRecommended --includeOptional --passive --locale en-US --Force"

# Recover working directory to the root.
WORKDIR "/"