# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


  on_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt-get --yes install ninja-build
        sudo apt-get --yes install cmake
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 15CF4D18AF4F7421
        sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main'
        sudo apt-get update
        sudo apt-get --yes install llvm-14
        sudo apt-get --yes install clang-14
        sudo apt-get --yes install clang-tidy-14
        sudo apt-get --yes install clang-format-14
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Collect information for clang-tidy-14
      run: |
        clang-tidy-14 --version
    - name: Collect information for clang-format-14
      run: |
        clang-format-14 --version
    - name: Test with pytest
      run: |
        python -m pytest -v --cov .


  on_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pytest-cov
        choco install ninja -Y
        #choco install llvm --version=14.0.1
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Collect information for clang-tidy
      run: |
        clang-tidy --version
    - name: Collect information for clang-format
      run: |
        clang-format --version
    - name: Test with pytest
      run: |
        python -m pytest -v --cov .


  on_macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pytest-cov
        brew install cmake
        brew install ninja
        #brew install llvm@14
        brew info llvm
        brew info --json=v1 llvm | jq .
        ls -la $(brew --prefix llvm)
        ls -la $(brew --prefix llvm)/bin
        #ln -s "$(brew --prefix llvm)/bin/clang-format" "/usr/local/bin/clang-format-14"
        #ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy-14"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Collect information for clang-tidy-14
      run: |
        clang-tidy-14 --version
    - name: Collect information for clang-format-14
      run: |
        clang-format-14 --version
    - name: Test with pytest
      run: |
        python -m pytest -v --cov .

